### ISSUE TITLE
Android issue running OpenELEC Helix

### ISSUE THREAD

**Issue by inthewayz** [mancuniancol/plugin.video.yts#1]
Working fine on a Windows machine but fetching data (after latest/oldest) I get script error at the top.

**Comment by mancuniancol** [comment]
This addon is still in beta. I have only tested in windows. If you give access to your log I will have something to work with. Otherwise, I couldn't reproduce the error.

**Comment by inthewayz** [comment]
Please let me know if you need anything else.

[01_KODI.txt](https://github.com/mancuniancol/plugin.video.yts/files/36744/01_KODI.txt)

**Comment by mancuniancol** [comment]
It seems you don't have installed the latest version of my tools.
https://github.com/mancuniancol/script.module.mctools/archive/V1.2.5.zip

Please, try with that version and let me know the results

**Comment by evensomuch** [comment]
Forgot my password...

I tried again with mctools 1.2.5 and it works great now. Thank you!
