### ISSUE TITLE
Incorrect durations

### ISSUE THREAD

**Issue by evensomuch** [mancuniancol/plugin.video.yts#2]
1080 -> All -> All -> Latest

Files can show 6000 minutes duration... None are correct.

A quick question too. What is the 3rd option for? The 9+ 8+?

**Comment by mancuniancol** [comment]
Are you using confluence skin? Because, I get the right value.  
Some skin give the value in seconds, instead of minutes. 
Could you confirm if you get the right values with confluence? In that case, contact your skin author.

**Comment by evensomuch** [comment]
Running Kodi Helix on Windows and OpenELEC Helix on Android both using Confluence. The same problem.

**Comment by evensomuch** [comment]
Just to add. Some are 90 minutes long showing 9200 minutes.

**Comment by mancuniancol** [comment]
I have Isengard and Jarvis with openelec and windows and the information is correct.  Not idea, why you are getting the wrong values.

**Comment by mancuniancol** [comment]
Could you confirm that you have version 2.9.0 for the Metahandler? http://offshoregit.com/pulsarunofficial/raw/master/script.module.metahandler/script.module.metahandler-2.9.0.zip

If you have previous version, you will need to clear the database after the update

**Comment by evensomuch** [comment]
I had 2.9.0 installed. I cleared the database. Same problem.

I've isolated it down to Helix. I updated to Isengard on the Windows machine and now durations are working fine. Is it something you can fix?

**Comment by mancuniancol** [comment]
You can make customized version for that version.  You need to modify the file tools2.py in the script.module.mctools.  That files is in the lib folder.  Just add /60 at the end and save.  That it will be the trick.

line 1113
 infoLabels['duration'] = duration /60

I will close this issue, because I don't support previous kodi version. Sorry.

**Comment by evensomuch** [comment]
Thanks for the fix.
