### ISSUE TITLE
Will not show links

### ISSUE THREAD

**Issue by theboy181** [mancuniancol/plugin.video.yts#3]
When I navigate through the menus and open latest, it will show the curl for a while then stop. if you keep doing that it will keep taking you a page deeper and you can select latest again but it will not show any links.

**Comment by mancuniancol** [comment]
I will need more information like the log, type of system that you have.  I've tested this morning and it is working.

Are you able to visit the page?  Have you checked your log? are you using Android? Have you ever connected before or it got broken with the last update? From where did you install it?

Any case, the first time, it will take time because it is downloading all the information for the movies.  But, you can short the time disabling the metainformation in the settings.

I've tested this morning and it works flawless.  Then it is something wrong in your side.  But, without more information, I cannot help you. Sorry. 

 I've uploaded the video.

https://vid.me/srsy

Disabling the metainformation
https://vid.me/KaEY

**Comment by theboy181** [comment]
http://pastebin.com/4bEBg1RR

I tried without meta data no luck.

I dont have access to the HTC right now, but I have my laptop and Torrentz Viewer plugin doing the same thing.

Im on Windows 7 64bit with the latest stable build from kodi.

I installed the plugin using the 1.6 unofficial pulsar repo and it worked fine. I later installed the repo using the repo from fusion.

I received a msg that the YTS viewer could not be updated shortly after that. I have tried to manually install the viewer since then without luck. 
On my laptop the same thing happened with the Fusion installed repo. I installed YTS viewer from fusion addon installer didnt work then installed manually then it did. I tried this method on the HTC but didnt work.. Im lost.

Please let me know if you need more info.

**Comment by mancuniancol** [comment]
Check version. I do not submit directly to fusion. Then, they don't have the latest version. If you want to use please, uninstall de provider repo and the viewers and the mc tools library. Otherwise, you will have a mix of versions that they don't play well together. I will check your log later. I do not support Android yet, though

**Comment by theboy181** [comment]
I removed everything and now when I try to install from 1.6 repo I get a dependency not met error.

**Comment by mancuniancol** [comment]
Yes, it seems a problem with the version. Please, check the version with this list. 

http://offshoregit.com/pulsarunofficial/raw/master/

That is from providers repo

**Comment by mancuniancol** [comment]
You need to install the extended info script. It is in the same repo

**Comment by mancuniancol** [comment]
I will leave that dependency optional for the next release, though. But, now it is mandatory. Please, check in the same list which extended script info version you need.

**Comment by theboy181** [comment]
I removed and reinstalled kodi and 1.0.6 repo. I don't see any viewers there now or the script.

**Comment by mancuniancol** [comment]
Did you check the url that I've posted before? That is the url that repo search. 
I will try to help tonight. I have to start to work sorry

**Comment by theboy181** [comment]
Will do. Have a great shift

**Comment by theboy181** [comment]
I was able to get it working but I had to manually install the extendedinfo yts viewer and the 1.0.6 repo. 

The first time I installed this all I did was install the 1.0.6 repo and install yts.  Had something changed from a week ago?

**Comment by theboy181** [comment]
On an other note 1.0.6 was missing all the viewers and pulsar stuff in the repo on my laptop but not my HTC. Confusing. My laptop was from a fresh install and the HTC was after removing a few of the repositorys and other items you suggested that could get in the way.

**Comment by mancuniancol** [comment]
Yes, I've added support to extended info script, but it is bringing more problems to install. Tomorrow, I will try to do something to improve that. About the repo. That which you are using is the most complete.

**Comment by mancuniancol** [comment]
I did several test doing clean install from openelec and windows machines and I don't have any trouble to install the addon from the tvaddons repo.  I don't know how to help you, because I cannot reproduce the problem :(

**Comment by theboy181** [comment]
This is really weird then. What would cause the repo not to show the viewers and the pulsar stuff. 

Did you exit kodi or just jump into the installation of the repo.

**Comment by theboy181** [comment]
Can teamview and watch me through the process.

**Comment by mancuniancol** [comment]
Yeah, but you could try first this another repo. Again. Disable or uninstall the providers unofficial repo to avoid conflict. 
http://tutvguia.xyz/repository.tutvguia/repository.tutvguia-1.0.1.zip

**Comment by theboy181** [comment]
You mean disable the uniffical pulsar repo I downloaded from the off shore github link you shared?

**Comment by mancuniancol** [comment]
Yes and any repo related. Because, that makes kodi confused. You should have just one repo for this kind of addons.

**Comment by theboy181** [comment]
I will have to test later. We are going to go swim with dolphins today. ;)

**Comment by theboy181** [comment]
I ran a quick test by disabling the 1.0.6 repo and it looks like tutvguia is working.. thanks. .

I look forward to our future releases that dont require the extended repo..
