### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by theboy181** [mancuniancol/plugin.video.yts#5]
Can you point me out on how to make this pluging navigate directly to the last place before showing the torrents. For example every time I use this plugin I have to navigate 4 pages. 

I would like to default the plugin to bring me to the final page with the following selections. 

All>all>1+>
I have never narrowed the search less than that and would like to simplify the process. 

Can you show me where in the plug I can modify it myself or add something to the plugin to change the search paths up on requests ?

Thanks. And stilly favorite pluging for torrents.

**Comment by mancuniancol** [comment]
You use the search option and save that option
