### ISSUE TITLE
YTS.AG is no longer responding here

### ISSUE THREAD

**Issue by inthewazyzz** [mancuniancol/plugin.video.yts#6]
Can you add support for https://yts.gs

**Comment by mancuniancol** [comment]
Did you change the Url in the settings? And is it not working?

**Comment by inthewazyzz** [comment]
Due to the website blockade in some countries sadly .ag is one of them blocked. gs is working but your add-on doesn't load anything after "Latest".

**Comment by mancuniancol** [comment]
I will check it

**Comment by mancuniancol** [comment]
The url works without any problem.  Please, disable the metainfomation because it is possible that it is making too slow.   You can also configure the metahandler script with a TheMovieDB key, you can get it for free, just creating an account.

**Comment by mancuniancol** [comment]
I will close this issue, because I couldn't reproduce in my side and it seems a problem with metainformation.
